### ISSUE TITLE
Incorrect deskewing of image

### ISSUE THREAD

**Issue by Rashmi002** [kakul/Alyn#4]
I have applied skew_detect and skew_correction on given image but its showing incorrect result. In image rectangle and text is  not aligned properly.

**Comment by kakul** [comment]
Is this the given initial image, or image generated after deskew?

**Comment by Rashmi002** [comment]
Image generated after deskew

**Comment by kakul** [comment]
Could you attach the initial image?

Probably the circles in the image are creating problems with hough transform calculations.

**Comment by Rashmi002** [comment]
![1 27](https://cloud.githubusercontent.com/assets/22294534/24355918/763d8786-1315-11e7-9ce7-37d046eb96a0.JPG)
Kindly consider this image as i have privacy issue so when you download it please remove it from this location.

**Comment by kakul** [comment]
Ok will try and let you know soon

**Comment by Rashmi002** [comment]
Shall i remove the image?

**Comment by kakul** [comment]
Yes

**Comment by kakul** [comment]
It worked correctly on the given image, without anything extra.

**Comment by Rashmi002** [comment]
Can you mail me result with given code?

**Comment by Rashmi002** [comment]
![aku28](https://cloud.githubusercontent.com/assets/22294534/24391793/acee74f4-13ae-11e7-91e5-4b1676583d23.jpg)
It's not working for this image. Check it out.

**Comment by kakul** [comment]
![tt](https://cloud.githubusercontent.com/assets/4489731/24391923/3e7a5de8-13af-11e7-84ac-a5174ca35c8f.jpg)

Well in my case the result image was this

**Comment by kakul** [comment]
Follow these steps:

pip install virtualenv (use sudo if required)

virtualenv any-name-of-your-choice
cd any-name-of-your-choice
pip install alyn

create a file test.py or simply open python interpreter and write the following code:

from alyn import *

d = Deskew(input_file='input.jpg', display='Y', output_file='output.jpg', r_angle=0)
d.deskew()

The output will be saved as output.jpg, once you close the preview display window

**Comment by Rashmi002** [comment]
Recently, image which i have uploaded, it's not working

**Comment by kakul** [comment]
In that case you will have to tweak the code a bit, change the default values that are used in skew angle calculation in skew_detect.py. You can supply your own values for sigma and number of peaks or modify the defaults in the code itself.

**Comment by kakul** [comment]
Try this for different values of sigma and number of peaks to find a fit that works best.

**Comment by Rashmi002** [comment]
from alyn import *

d = Deskew(input_file='input.jpg', display='Y', output_file='output.jpg', r_angle=0)
d.deskew()

In this case error is generated.
from skimage.feature import canny
ImportError: cannot import name canny

**Comment by kakul** [comment]
Are you using skimage version < 0.10?

**Comment by kakul** [comment]
@Rashmi002 did the skew detect parameters work?

**Comment by Rashmi002** [comment]
I am using skimage 0.13 version. How can i know skew detect parameter is working or not?

**Comment by Rashmi002** [comment]
skew detect parameter is not working properly.

**Comment by Rashmi002** [comment]
how can i finetune it?

**Comment by kakul** [comment]
https://github.com/kakul/Alyn/blob/master/alyn/skew_detect.py#L23
https://github.com/kakul/Alyn/blob/master/alyn/skew_detect.py#L25

Change these values.

**Comment by Rashmi002** [comment]
ok..I will let you know.

**Comment by kakul** [comment]
Hi @Rashmi002, did the code work?

**Comment by kakul** [comment]
Closing this.

**Comment by pharrellyhy** [comment]
Hi, 
I've played around deskew for a while and found if the image contains not only text but also picture, it didn't work well. One workaround is I can crop the region which only contains text. This solution may not work well too since I don't know which part of image contains only text. Do you have any idea on this situation? Below is my test image:
![92_10](https://user-images.githubusercontent.com/16664753/39920975-bc7109fc-554b-11e8-99eb-3051e578a529.jpg)

**Comment by pharrellyhy** [comment]
I also noticed that if the image contains more than one page, like the one I attached above, deskew will fail.
