### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by akiradeveloper** [kakul/Alyn#6]
My concern is skew_detect only and I installed this software via pip.

But there is no command installed. How can I use this?

I git-clone this repo and run skew_detect.py but it requires python-tk. Because I should run this server there is no GUI. Why does it depend on python-tk? The dependency is strange to me.

**Comment by kakul** [comment]
Hey @akiradeveloper python-tk is required for previewing the display image. I initially created this module for compatibility with computers having GUI. I am working on making this compatible with servers as well. Thanks for raising this issue

**Comment by akiradeveloper** [comment]
Thanks @kakul, I am looking forward to the update

**Comment by kakul** [comment]
Hi @akiradeveloper 
You could try this:

```
from alyn import SkewDetect
sd = SkewDetect(input_file='path-to-image-file', display_output='Yes')
sd.run()
```

**Comment by akiradeveloper** [comment]
with the pip version?

**Comment by kakul** [comment]
Yes

**Comment by akiradeveloper** [comment]
doesn't it depends on any GUI?

**Comment by kakul** [comment]
Deskew depends optionally on GUI to preview the deskewed image, but SkewDetect doesn't need it.

**Comment by akiradeveloper** [comment]
OK. I ran it

```
>>> from alyn import SkewDetect
>>> sd = SkewDetect(input_file="hoge0.png", display_output='Yes')
>>> sd.run()
Image File: /home/akira/tess-ex/hoge0.png
Angle bins: [[], [85.977653631284895, 85.977653631284895], [-4.5251396648044766, -2.5139664804469359], []]
Estimated Angle: 85.9776536313
Average Deviation from pi/4: 41.9832402235
```

How can I read this result? The image is only 4 degrees skewed counter-clockwise. Is this the correct result?

**Comment by kakul** [comment]
Yes the result is correct. You should refer the estimated angle value and the Average deviation value'

The algorithm decides, the approximated skew based on voting procedure to guess the best axis of skew.

**Comment by kakul** [comment]
There might be some cases when the skew angle is around 45/135 degrees, in that case it is difficult to guess the correct axis.

Or when there are less number of straight lines/edges to determine the precise skew angle.

**Comment by akiradeveloper** [comment]
Estimate angle from where?
pi/4 from where?

I didn't understand where is the base.

**Comment by akiradeveloper** [comment]
The image is 4 degrees skewed counter-clockwise from north to north west.

**Comment by kakul** [comment]
[https://github.com/kakul/Alyn/blob/master/test_data/0.jpg](Image)

This represents 0 degree.

A vertical line will represent 90 degrees.

Your image is at 85.9 degrees, hence 4 degrees less from vertical.

**Comment by kakul** [comment]
@akiradeveloper did it work for you?
